"""Clean schema init

Revision ID: 749c91f9f593
Revises: 
Create Date: 2025-06-05 06:29:39.015550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749c91f9f593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('interests', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('opening_time', sa.String(), nullable=True),
    sa.Column('closing_time', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('price_range', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points_of_interest')
    # ### end Alembic commands ###
